version: "3.3"

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracledatabase
    volumes:
      - /home/your-path/oracle-volume:/opt/oracle/oradata
      - /home/your-path/startupscripts:/container-entrypoint-startdb.d
      - /home/your-path/backup:/backup
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: root
      ORACLE_DATABASE: geraldine
      APP_USER: dbuser
      APP_USER_PASSWORD: dbuser

volumes:
  oracle-volume:
  startupscripts:
  backup:
