-- LEFT JOIN
-- SELECT * FROM table1 LEFT JOIN table2 ON table1.id = table2.id

-- LEFT JOIN adalah mekanisme JOIN seperti INNER JOIN,
-- namun semua data di table pertama akan diambil semua, meskipun tidak memiliki relasi di table kedua
-- Jika ada yang tidak memiliki relasi di table kedua, maka hasilnya akan NULL


-- Munculkan semua data dari table ORDERS, walau tidak ada relasi di table EMPLOYEES
SELECT O.ORDER_ID, O.STATUS, E.FIRST_NAME, E.LAST_NAME
FROM ORDERS O
LEFT JOIN EMPLOYEES E ON E.EMPLOYEE_ID = O.SALESMAN_ID
ORDER BY O.ORDER_DATE DESC;


-- MULTIPLE LEFT JOIN
SELECT O.ORDER_ID, O.STATUS, E.FIRST_NAME, E.LAST_NAME
FROM ORDERS O
LEFT JOIN EMPLOYEES E ON E.EMPLOYEE_ID = O.SALESMAN_ID
LEFT JOIN CUSTOMERS C ON C.CUSTOMER_ID = O.CUSTOMER_ID
ORDER BY O.ORDER_DATE DESC;


-- MENGGUNAKAN USING
SELECT NAME, ORDER_ID, STATUS, ORDER_DATE
FROM CUSTOMERS
LEFT JOIN ORDERS USING (CUSTOMER_ID)
ORDER BY ORDER_DATE DESC;


-- MENAMBAHKAN KONDISI WHERE
SELECT O.ORDER_ID, O.STATUS, E.FIRST_NAME, E.LAST_NAME
FROM ORDERS O
LEFT JOIN EMPLOYEES E ON E.EMPLOYEE_ID = O.SALESMAN_ID
WHERE O.ORDER_ID = 58;


-- DENGAN TAMBAH KONDISI PADA JOIN (maka hasilnya akan berbeda)
SELECT O.ORDER_ID, O.STATUS, E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME
FROM ORDERS O
LEFT JOIN EMPLOYEES E ON E.EMPLOYEE_ID = O.SALESMAN_ID AND E.EMPLOYEE_ID = 1
AND O.ORDER_ID = 58;