-- SELF JOIN
-- ADALAH SEBUAH JOIN YANG MENGABUNGKAN DENGAN DIRINYA SENDIRI
-- SELF JOIN DIGUNAKAN UNTUK MENYATUKAN DATA DENGAN DIRINYA SENDIRI
-- SELECT COLUMN_LIST FROM TABLE1 T1 JOIN TABLE1 T2 ON T1.COLUMN_NAME = T2.COLUMN_NAME
-- DENGAN ADANYA ALIAS T1 DAN T2, MAKA KITA DAPAT MENYATUKAN DATA DENGAN DIRINYA SENDIRI



-- MENAMPILKAN EMPLOYEE NAME, MANAGER NAME, JOB TITLE
-- DARI TABEL EMPLOYEES
-- DIMANA EMPLOYEE NAME ADALAH FIRST NAME DAN LAST NAME
-- MANAGER NAME ADALAH FIRST NAME DAN LAST NAME
-- JOB TITLE
-- DIURUTKAN BERDASARKAN MANAGER NAME SECARA ASCENDING
-- JOINT TABEL EMPLOYEES DENGAN DIRINYA SENDIRI
SELECT
    (E.FIRST_NAME || ' ' || E.LAST_NAME) AS EMPLOYEE_NAME,
    (M.FIRST_NAME || ' ' || M.LAST_NAME) AS MANAGER_NAME,
    E.JOB_TITLE
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M ON M.EMPLOYEE_ID = E.MANAGER_ID
ORDER BY MANAGER_NAME;


-- MENAMPILKAN HIRE DATE, EMPLOYEE1, EMPLOYEE2
-- DARI TABEL EMPLOYEES
-- DIMANA EMPLOYEE1 ADALAH FIRST NAME DAN LAST NAME
-- EMPLOYEE2 ADALAH FIRST NAME DAN LAST NAME
-- DIURUTKAN BERDASARKAN HIRE DATE SECARA DESCENDING
-- JOINT TABEL EMPLOYEES DENGAN DIRINYA SENDIRI
-- DENGAN SYARAT EMPLOYEE2.EMPLOYEE_ID > EMPLOYEE1.EMPLOYEE_ID
-- DAN EMPLOYEE2.HIRE_DATE = EMPLOYEE1.HIRE_DATE
SELECT
    E1.HIRE_DATE,
    (E1.FIRST_NAME || ' ' || E1.LAST_NAME) AS EMPLOYEE1,
    (E2.FIRST_NAME || ' ' || E2.LAST_NAME) AS EMPLOYEE2
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2 ON E2.EMPLOYEE_ID > E1.EMPLOYEE_ID
AND E2.HIRE_DATE = E1.HIRE_DATE
ORDER BY E1.HIRE_DATE DESC, EMPLOYEE1, EMPLOYEE2;

-- Query ini digunakan untuk mencari pasangan karyawan yang direkrut pada tanggal yang sama,
-- tetapi dengan EMPLOYEE_ID yang berbeda.
-- Jika tidak ada pasangan yang cocok, kolom EMPLOYEE2 akan menampilkan NULL.