-- OPERATOR EXISTS
-- EXISTS adalah operator boolean yang mengembalikan benar atau salah

-- SELECT *
-- FROM TABLE_NAME
-- WHERE EXISTS (SELECT column_name FROM TABLE_NAME WHERE condition);


-- PENGGUNAAN EXISTS
SELECT NAME
FROM CUSTOMERS C
WHERE 
    EXISTS (
        SELECT 1 -- SELECT 1 karena tidak memerlukan data apapun
        FROM ORDERS O
        WHERE O.CUSTOMER_ID = C.CUSTOMER_ID
    );

-- BAGAIMANA CARANYA PENGGUNAAN EXISTS DALAM -- Update rows in a Table

UPDATE WAREHOUSES W
SET WAREHOUSE_NAME = WAREHOUSE_NAME || ', USA'
WHERE EXISTS (
    SELECT 1 
    FROM LOCATIONS L
    WHERE L.COUNTRY_ID = 'US'
    AND L.LOCATION_ID = W.LOCATION_ID
);

SELECT * FROM WAREHOUSES WHERE WAREHOUSE_NAME LIKE '%USA%';

-- BAGAIMANA CARANYA PENGGUNAAN EXISTS DALAM -- insert rows in a Table

INSERT INTO
CUSTOMERS_2016 (
    company,
    first_name,
    last_name,
    email
)SELECT
    NAME as company,
    FIRST_NAME,
    LAST_NAME,
    EMAIL
FROM CUSTOMERS C
JOIN CONTACTS CT ON CT.CUSTOMER_ID = C.CUSTOMER_ID
WHERE 
    EXISTS (
        SELECT 1 
        FROM ORDERS O
        WHERE O.CUSTOMER_ID = C.CUSTOMER_ID
        AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2016
    )
ORDER BY company;


SELECT * FROM CUSTOMERS_2016;


-- SEKARANG BAGAIMANA PERBANDINGAN OPERATOR EXISTS DENGAN OPERATOR IN
-- OPERATOR EXISTS ITU BERHENTI MELAKUKAN SCAN SETELAH SUBQUERY MENGHASILKAN BARIS PERTAMA BERNILAI TRUE ATAU FALSE
-- OPERATOR IN DIA AKAN MEMBANDINGKAN SEMUANYA SAMPAI SELESAI
-- JADI KALO INGIN LEBIH EFISIEN GUNAKAN EXISTS

-- COBA MENGGUNAKAN IN
-- JIKA MENGGUNAKAN IN MAKA AKAN MENGHASILKAN ERROR
-- KARENA SUBQUERY INI MENGHASILKAN NULL, OPERATOR IN ITU MEMBANDINGKAN SEMUA DATA
SELECT * 
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (
    SELECT NULL FROM DUAL
);


-- COBA MENGGUNAKAN EXISTS
-- PERBEDAAN DENGAN IN, EXISTS TIDAK AKAN MENGHASILKAN ERROR
-- KARENA EXISTS TIDAK MEMBANDINGKAN DATA
-- HANYA MEMBANDINGKAN TRUE ATAU FALSE
SELECT *
FROM CUSTOMERS
WHERE EXISTS (
    SELECT NULL FROM DUAL
);

-- UNTUK EXISTS ADALAH OPERATOR BENAR ATAU SALAH BUKAN MEMBANDINGKAN VALUE-NYA
