-- OPERATOR NOT EXISTS
-- adalah operator yang bekerja kebalikan dari operator EXISTS. 
-- Operator ini akan menghasilkan nilai TRUE jika subquery yang diberikan tidak menghasilkan baris data,
--  dan FALSE jika subquery menghasilkan baris data.

-- SELECT *
-- FROM TABLE_NAME
-- WHERE NOT EXISTS (
--     SUBQUERY
-- );

SELECT NAME
FROM CUSTOMERS C
WHERE NOT EXISTS (
    SELECT NULL
    FROM ORDERS O
    WHERE C.CUSTOMER_ID = O.CUSTOMER_ID
)
ORDER BY NAME;


-- MEMBUAT TABLE DENGAN BANTUAN NOT EXISTS
CREATE TABLE CUSTOMERS_WITHOUT_ORDERS AS
SELECT NAME
FROM CUSTOMERS C
WHERE NOT EXISTS (
    SELECT NULL
    FROM ORDERS O
    WHERE O.CUSTOMER_ID = C.CUSTOMER_ID
);


SELECT * FROM CUSTOMERS_WITHOUT_ORDERS;


-- cara menggunakan not exists dalam Update
UPDATE CUSTOMERS
SET CREDIT_LIMIT=0
WHERE not exists (
    SELECT NULL
    FROM ORDERS O
    WHERE O.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
    AND EXTRACT(YEAR FROM ORDER_DATE) = 2016
);


-- SEKARANG BAGAIMANA JIKA DELETE
DELETE FROM CUSTOMERS C
WHERE NOT EXISTS (
    SELECT NULL
    FROM ORDERS O
    WHERE O.CUSTOMER_ID = C.CUSTOMER_ID
    AND EXTRACT(YEAR FROM ORDER_DATE) IN (2016, 2017)
);