-- OPERATOR ANY
-- digunakan untuk membandingkan nilai dengan daftar atau subquery
-- OPERATOR ANY ( V1, V2, V3, ... )
-- atau
-- OPERATOR ANY ( subquery )

-- SELECT *
-- FROM TABLE_NAME
-- WHERE COLUMN_NAME > ANY (
--      V1,
--      V2,
--      V3
-- );

-- ini sama dengan

-- SELECT *
-- FROM TABLE_NAME
-- WHERE COLUMN_NAME > V1
-- OR COLUMN_NAME > V2
-- OR COLUMN_NAME > V3;

-- ANY MENGGUNAKAN SUBQUERY
-- dengan operasi perbandingan lebih dari
SELECT PRODUCT_NAME, LIST_PRICE
FROM PRODUCTS
WHERE LIST_PRICE > ANY (
    SELECT LIST_PRICE
    FROM PRODUCTS
    WHERE CATEGORY_ID = 1
)
ORDER BY PRODUCT_NAME;

-- kita gunakan exists untuk menghasilkan hasil yang sama
SELECT PRODUCT_NAME, LIST_PRICE
FROM PRODUCTS P1
WHERE EXISTS(
    SELECT LIST_PRICE
    FROM PRODUCTS P2
    WHERE P2.CATEGORY_ID = 1
    AND P1.LIST_PRICE > P2.LIST_PRICE
)


-- DI ORACEL ADA JUGA OPERATOR SOME YANG SAMA DENGAN ANY
SELECT PRODUCT_NAME, LIST_PRICE
FROM PRODUCTS
WHERE LIST_PRICE > SOME (
    SELECT LIST_PRICE
    FROM PRODUCTS
    WHERE CATEGORY_ID = 1
)
ORDER BY PRODUCT_NAME;



-- SEKARANG KITA COBA DENGAN OPERASI MATEMATIKA
-- MEMBUAT KOLOM YANG DIBANDINGKAN DENGAN DAFTAR APAPUN

-- COL = APAPUN ( DAFTAR )
SELECT
    PRODUCT_NAME,
    LIST_PRICE
FROM PRODUCTS
WHERE
    LIST_PRICE = ANY(
        2200,
        2259.99,
        2269.99
    )
    AND CATEGORY_ID = 1;


-- COL != APAPUN ( DAFTAR )
SELECT
    PRODUCT_NAME,
    LIST_PRICE
FROM PRODUCTS
WHERE
    LIST_PRICE != ANY(
        2200,
        2259.99,
        2269.99
    )
AND CATEGORY_ID = 1
ORDER BY LIST_PRICE DESC;


-- COL > APAPUN ( DAFTAR )
SELECT
    PRODUCT_NAME,
    LIST_PRICE
FROM PRODUCTS
WHERE
    LIST_PRICE > ANY(
        2200,
        2259.99,
        2269.99
    )
    AND CATEGORY_ID = 1