-- COLUMN IDENTITY
-- digunakan untuk menentukan kolom numerik yang dibuat secara otomatis untuk sebuah tabel.
-- mirip dengan AUTO_INCREMENT di MySQL dan SERIAL di PostgreSQL. atau IDENTITY di SQL Server.

GENERATED [ALWAYS | BY DEFAULT [ON NULL] ]
AS IDENTITY [ ( IDENTITY_OPTIONS ) ]

-- GENERATED ALWAYS: Oracle selaalu menghasilkan nilai untuk kolom identitas.
-- Mencoba memasukan nilai ke dalam kolom identitas akan menghasilkan kesalahan.

-- GENERATED BY DEFAULT: Oracle akan menghasilkan nilai untuk kolom identitas jika anda tidak memberi nilai secara otomatis.
-- Jika memberikan nilai, maka nilai tersebut akan digunakan.

-- GENERATED ON NULL: Oracle akan menghasilkan nilai untuk kolom identitas jika anda memberikan nilai NULL atau tidak memberikan nilai sama sekali.

-- OPSI IDENTITY
-- START WITH: initial_value mengontrol nilai awal yang akan digunakan untuk kolom identitas.
-- nilai default adalah 1.
-- INCREMENT BY: increment_value mengontrol jumlah yang akan ditambahkan ke kolom identitas setiap kali baris baru dimasukan.
-- nilai default adalah 1.
-- CACHE: mendefinisikan sejumlah nilai yang harus dihasilkan oracle sebelumnya untuk menginkatkan kinerja.
-- menggunakan opsi ini untuk kolom yang memiliki banyak sisiapan.
-- cache_value mengontrol jumlah nilai yang akan disimpan dalam cache.
-- nilai default adalah 20.